# Generated by Django 5.1 on 2024-08-19 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_clicked',
            field=models.BooleanField(default=False),
        ),
    ]
